update workflow

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -16,7 +16,9 @@ on:
     branches:
       - main
       - release-*
-
+env:
+  GO_VERSION: 1.25.7
+  ARTIFACT_DIR: artifacts
 jobs:
   workflow-scratch:
     runs-on: ubuntu-latest
@@ -24,6 +26,7 @@ jobs:
     permissions:
       contents: write
       id-token: write
+      pull-requests: read
     env:
       GOMEMLIMIT: 2GiB
       TRIVY_SKIP_DB_UPDATE: true
@@ -40,7 +43,7 @@ jobs:
       - name: Setup go
         uses: actions/setup-go@v6
         with:
-          go-version: 1.25.7
+          go-version: ${{ env.GO_VERSION }}
 
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -50,44 +53,50 @@ jobs:
       - name: Create artifact directory
         run: mkdir -p artifacts
 
+
       # https://golangci-lint.run/docs/welcome/install/ci/
+      # https://github.com/golangci/golangci-lint-action
       - name: Lint go files
         id: lint-go-files
         uses: golangci/golangci-lint-action@v9
         with:
           version: v2.10.1
+          problem-matchers: true
           args: --config=./.golangci-config.yaml
         continue-on-error: true
 
-      - name: Create artifact for lint-go-files
-        run: |
-          echo "${{steps.lint-go-files.outputs.stdout}}" > artifacts/golangci-lint-results.stdout
-          echo "${{steps.lint-go-files.outputs.stderr}}" > artifacts/golangci-lint-results.stderr
 
+      # https://github.com/marketplace/actions/markdown-linting-action
       - name: Lint markdown files
         id: lint-markdown
         uses: avto-dev/markdown-lint@v1
         with:
           args: ./
           config: ./.markdown-lint.yml
+          output: "$ARTIFACT_DIR/markdown-lint-results.txt"
         continue-on-error: true
 
-      - name: Create artifact for lint-markdown
-        run: |
-          echo "${{steps.lint-markdown.outputs.stdout}}" > artifacts/markdown-lint-results.stdout
-          echo "${{steps.lint-markdown.outputs.stderr}}" > artifacts/markdown-lint-results.stderr
+      - name: Show markdown lint results
+        if: steps.lint-markdown.outcome == 'failure'
+        run: cat "$ARTIFACT_DIR/markdown-lint-results.txt"
 
+
+      # https://github.com/hadolint/hadolint-action
+      # Note this has to be called multiple times for multiple dockerfiles
       - name: Lint dockerfile
         id: lint-dockerfile
         uses: hadolint/hadolint-action@v3.1.0
         with:
           dockerfile: ./tests/integration/Dockerfile.a
+          output: "$ARTIFACT_DIR/hadolint-Dockerfile.a.txt"
+          failure-threshold: error
+          no-fail: true
         continue-on-error: true
 
-      - name: Create artifact for lint-dockerfile
-        run: |
-          echo "${{steps.lint-dockerfile.outputs.stdout}}" > artifacts/hadolint-results.stdout
-          echo "${{steps.lint-dockerfile.outputs.stderr}}" > artifacts/hadolint-results.stderr
+      - name: Show hadolint results
+        if: steps.lint-dockerfile.outcome == 'failure'
+        run: cat "$ARTIFACT_DIR/hadolint-results.txt"
+
 
       # https://github.com/marketplace/actions/shellcheck
       - name: Lint shell scripts
@@ -95,10 +104,6 @@ jobs:
         uses: ludeeus/action-shellcheck@master
         continue-on-error: true
 
-      - name: Create artifact for lint-shell
-        run: |
-          echo "${{steps.lint-shell.outputs.stdout}}" > artifacts/shellcheck-results.stdout
-          echo "${{steps.lint-shell.outputs.stderr}}" > artifacts/shellcheck-results.stderr
 
       # https://github.com/gitleaks/gitleaks-action
       # Get free license key from https://gitleaks.io/
@@ -109,17 +114,26 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Only required for Organizations, not personal accounts.
 
-      - name: Create artifact for gitleaks
-        run: |
-          echo "${{steps.gitleaks.outputs.stdout}}" > artifacts/gitleaks-results.stdout
-          echo "${{steps.gitleaks.outputs.stderr}}" > artifacts/gitleaks-results.stderr
 
+      # https://github.com/aquasecurity/trivy-action
       # calling once here to populate the cache, and then skipping setup in the trivy-action step to save time
       - name: Manual Trivy Setup
         uses: aquasecurity/setup-trivy@v0.2.0
         with:
           cache: true
           version: v0.69.2
+
+      - name: Find pull request ID
+        run: |
+            PR_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+              "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ github.ref_name }}&state=open")
+            PR_ID=$(echo "$PR_DATA" | jq -r '.[0].number')
+
+            if [ "$PR_ID" != "null" ]; then
+              echo "pull_request_id=$PR_ID" >> $GITHUB_ENV
+            else
+              echo "No open pull request found for this branch."
+            fi
 
       - name: Check for vulnerabilities
         uses: aquasecurity/trivy-action@master
@@ -128,7 +142,7 @@ jobs:
           severity: 'CRITICAL,HIGH'
           ignore-unfixed: true
           format: 'table'
-          output: 'artifacts/trivy-vuln-results.txt'
+          output: "$ARTIFACT_DIR/trivy-vuln-results.txt"
           skip-setup-trivy: true
           exit-code: 1
           trivy-config: ./.trivy.yaml
@@ -145,7 +159,7 @@ jobs:
           severity: 'CRITICAL,HIGH,UNKNOWN'
           ignore-unfixed: true
           format: 'table'
-          output: 'artifacts/trivy-license-results.txt'
+          output: "$ARTIFACT_DIR/trivy-license-results.txt"
           skip-setup-trivy: true
           exit-code: 1
           trivy-config: ./.trivy.yaml
@@ -156,7 +170,7 @@ jobs:
       # the results
       - name: Run govulncheck
         run: |
-          go run golang.org/x/vuln/cmd/govulncheck@latest ./... 2>&1 | tee artifacts/govulncheck-results.txt
+          go run golang.org/x/vuln/cmd/govulncheck@latest ./... 2>&1 | tee "$ARTIFACT_DIR/govulncheck-results.txt"
         continue-on-error: true
 
 
@@ -164,22 +178,20 @@ jobs:
       - name: Unit tests
         run: |
           mkdir -p cov
-          go test -count=1 -v -race -coverpkg=./lib ./lib/... -args -test.gocoverdir="$PWD/cov" 2>&1 | tee artifacts/go-test-output.txt
+          go test -count=1 -v -race -coverpkg=./lib ./lib/... -args -test.gocoverdir="$PWD/cov" 2>&1 | tee "$ARTIFACT_DIR/go-test-output.txt"
         continue-on-error: false
 
       - name: Generate coverage report
         run: |
-          go tool covdata textfmt -i="$PWD/cov" -o=artifacts/coverage.out
+          go tool covdata textfmt -i="$PWD/cov" -o="$ARTIFACT_DIR/coverage.out"
 
       # Display coverage summary
       - name: Display coverage summary
         run: |
-          echo "========================================" | tee artifacts/go-test-coverage-summary.txt
-          echo "Coverage Summary"                         | tee -a artifacts/go-test-coverage-summary.txt
-          echo "========================================" | tee -a artifacts/go-test-coverage-summary.txt
-          go tool covdata percent -i="$PWD/cov"      2>&1 | tee -a artifacts/go-test-coverage-summary.txt
-          echo "========================================" | tee -a artifacts/go-test-coverage-summary.txt
+          go tool covdata percent -i="$PWD/cov" 2>&1 | tee -a "$ARTIFACT_DIR/go-test-coverage-summary.txt"
 
+
+      # https://github.com/vladopajic/go-test-coverage/blob/main/docs/github_action.md
       # https://github.com/vladopajic/go-test-coverage/blob/main/README.md#configuration
       - name: Check test coverage
         id: check-coverage
@@ -188,10 +200,25 @@ jobs:
           config: ./.testcoverage.yml
         continue-on-error: true
 
-      - name: Create artifact for check-coverage
-        run: |
-          echo "${{steps.check-coverage.outputs.stdout}}" > artifacts/check-coverage-results.stdout
-          echo "${{steps.check-coverage.outputs.stderr}}" > artifacts/check-coverage-results.stderr
+
+
+      - name: Post coverage report
+        if: env.pull_request_id
+        uses: thollander/actions-comment-pull-request@v3
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          comment-tag: coverage-report
+          pr-number: ${{ env.pull_request_id }}
+          message: |
+            go-test-coverage report:
+            ```
+            ${{ fromJSON(steps.coverage.outputs.report) }}```
+
+      - name: "Evaluate coverage result"
+        if: steps.coverage.outcome == 'failure'
+        shell: bash
+        run: echo "coverage check failed" && exit 1
+
 
       - name: Upload artifacts
         uses: actions/upload-artifact@v5
@@ -199,7 +226,7 @@ jobs:
           name: ci-artifacts
           retention-days: 7
           if-no-files-found: ignore
-          path: artifacts/*
+          path: "$ARTIFACT_DIR"/*
 
       - name: Check for failure
         if: ${{ failure() }}
